#!/bin/sh
# Author       : Daniel Liljeberg <danielliljeberg@spray.se>
# Description  : Change author name of authors old commits.
# $Id$

if [ "$#" -ne 2 -o "$1" = "--help" ]; then
  echo "Usage: $0 old-user-name new-user-name"
  exit
fi

echo -n "Are you sure you wish to change the author of all commits made by '$1' to '$2'? [Y/n] "
read DOIT

if [ "$DOIT" = "y" -o "$DOIT" = "Y" ]; then
  for f in `svn log | grep "^r[0-9]* | $1 |" | cut -c 2- | awk '{print $1}'`
  do
    svn propset --revprop -r $f svn:author $2
  done
  echo "Done"
else
  echo "Aborting!"
fi
